# Generated by Django 5.2 on 2025-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('ContactName', models.CharField(max_length=100)),
                ('ContactTitle', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('Region', models.CharField(blank=True, max_length=50, null=True)),
                ('PostalCode', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Customers',
                'managed': True,
            },
        ),
    ]
