# Generated by Django 5.2 on 2025-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Fax',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
